version: '3.8'
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - db

  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  auth_queue:
    build:
      context: ./auth
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
      - db

  costomer_queue:
    build:
      context: ./customers
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
