# Generated by Django 4.0.5 on 2022-07-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='keja_tenant_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('my_active_rooms', models.IntegerField(default=0)),
                ('expected_rent', models.IntegerField(default=0)),
                ('pending_charges', models.IntegerField(default=0)),
                ('my_pending_rooms', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant.users_model')),
            ],
        ),
        migrations.CreateModel(
            name='keja_invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=200)),
                ('invoice_name', models.CharField(max_length=200)),
                ('invoice_status', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=200)),
                ('invoice_date', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.users_model')),
            ],
        ),
    ]
