# Generated by Django 4.0.4 on 2022-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='O5ycml9H3rm5QTs2VeTPRyAaAHs2VDiS', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=8156, max_length=255),
        ),
    ]
