# Generated by Django 4.0.4 on 2022-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_activationtoken_alter_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='oFvqOIcQmOzueNO1OxeKcKDoABWWwxgJ', max_length=255),
        ),
    ]
