# Generated by Django 4.0.4 on 2022-05-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(blank=True, default='aV3vzA4UbqFcwJAWTqfDI8HeyfiDKvSn', max_length=255, null=True),
        ),
    ]
