# Generated by Django 4.0.5 on 2022-07-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_appartments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apartment_name', models.CharField(max_length=100)),
                ('apartment_id', models.CharField(max_length=100)),
                ('apartment_no_of_units', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='host_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_id', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=100)),
                ('host_email', models.EmailField(max_length=100)),
                ('host_phone', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='room_models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_id', models.CharField(max_length=100)),
                ('room_status', models.CharField(max_length=100)),
                ('room_image', models.CharField(max_length=100)),
                ('room_price', models.FloatField(default=0)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host_appartments')),
                ('room_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host_model')),
                ('room_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.users_model')),
            ],
        ),
        migrations.CreateModel(
            name='tenat_flow_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host_model')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.room_models')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.users_model')),
            ],
        ),
        migrations.CreateModel(
            name='host_recent_transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_to', models.CharField(max_length=100)),
                ('transaction_from', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host_model')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.room_models')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.users_model')),
            ],
        ),
        migrations.CreateModel(
            name='host_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expences', models.FloatField(default=0)),
                ('revenue', models.FloatField(default=0)),
                ('statment_of_operations', models.FloatField(default=0)),
                ('pending_charges', models.FloatField(default=0)),
                ('automate_payments', models.BooleanField(default=False)),
                ('automate_managements', models.BooleanField(default=False)),
                ('house_maintanance', models.IntegerField(default=0)),
                ('pending_payout', models.FloatField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('vacants', models.IntegerField(default=0)),
                ('active_deposits', models.FloatField(default=0)),
                ('on_hold_deposits', models.FloatField(default=0)),
                ('pending_deposits', models.FloatField(default=0)),
                ('booked_listings', models.IntegerField(default=0)),
                ('active_clients', models.IntegerField(default=0)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='host.host_model')),
            ],
        ),
        migrations.AddField(
            model_name='host_appartments',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host_model'),
        ),
        migrations.CreateModel(
            name='billing_activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host_model')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.users_model')),
            ],
        ),
    ]
